In [1]:
from pszt import net
import numpy as np

In [2]:
mlp = net.MLP()

In [3]:
mlp.print_layers()

In [4]:
x_train = np.load('x_train.npy')
y_train = np.load('y_train.npy')
print(f'x_train.shape: {x_train.shape}, y_train.shape: {y_train.shape}')

x_train.shape: (1000, 8257), y_train.shape: (1000, 3)


In [5]:
mlp.add_layer(input_dim=x_train.shape[1], output_dim=4, activation="sigmoid")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 4, activation: sigmoid


In [6]:
mlp.add_layer(input_dim=4, output_dim=3, activation="softmax")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 4, activation: sigmoid
2. Layer - input_dim: 4, output_dim: 3, activation: softmax


In [7]:
mlp.init_layers()

In [8]:
mlp.param_values['w2'].shape

(4, 3)

In [9]:
for i, layer in reversed(list(enumerate(mlp.layers, start=1))):
    print(i)
    print(layer)

2
{'input_dim': 4, 'output_dim': 3, 'activation': 'softmax'}
1
{'input_dim': 8257, 'output_dim': 4, 'activation': 'sigmoid'}


In [10]:
mlp.train(x=x_train, y_true=y_train, epochs=200)

loss: 1097.12, accuracy: 55.5%
loss: 958.98, accuracy: 55.5%
loss: 939.45, accuracy: 55.5%
loss: 933.38, accuracy: 55.5%
loss: 930.80, accuracy: 55.5%
loss: 929.48, accuracy: 55.5%
loss: 928.67, accuracy: 55.5%
loss: 928.06, accuracy: 55.5%
loss: 927.51, accuracy: 55.5%
loss: 926.98, accuracy: 55.5%
loss: 926.42, accuracy: 55.5%
loss: 925.84, accuracy: 55.5%
loss: 925.21, accuracy: 55.5%
loss: 924.52, accuracy: 55.5%
loss: 923.78, accuracy: 55.5%
loss: 922.96, accuracy: 55.5%
loss: 922.07, accuracy: 55.5%
loss: 921.09, accuracy: 55.5%
loss: 920.02, accuracy: 55.5%
loss: 918.85, accuracy: 55.5%
loss: 917.57, accuracy: 55.5%
loss: 916.17, accuracy: 55.5%
loss: 914.64, accuracy: 55.5%
loss: 912.97, accuracy: 55.5%
loss: 911.15, accuracy: 55.5%
loss: 909.18, accuracy: 55.5%
loss: 907.04, accuracy: 55.5%
loss: 904.73, accuracy: 55.5%
loss: 902.24, accuracy: 55.5%
loss: 899.56, accuracy: 55.5%
loss: 896.68, accuracy: 55.5%
loss: 893.61, accuracy: 55.5%
loss: 890.35, accuracy: 55.5%
loss: 886

In [11]:
mlp.param_values['w1']

array([[ 0.0007846 ,  0.0098915 ,  0.00588264,  0.00386183],
       [ 0.00133661,  0.00364618, -0.00849613,  0.00188632],
       [-0.00809534, -0.01000073, -0.01896368, -0.014173  ],
       ...,
       [ 0.00687509,  0.00707646,  0.00959992,  0.00111735],
       [ 0.00540036,  0.00473374,  0.00936287,  0.00786482],
       [ 0.00950685,  0.01600886,  0.02002699,  0.01869586]])

In [12]:
a2 = mlp.memory['a2']
a2

array([[0.0349679 , 0.91431855, 0.05071355],
       [0.0254335 , 0.93318589, 0.04138061],
       [0.33026279, 0.51962843, 0.15010877],
       ...,
       [0.07500288, 0.8486338 , 0.07636331],
       [0.66713795, 0.18517071, 0.14769134],
       [0.02154983, 0.9386238 , 0.03982637]])

In [13]:
correct_pred = 0
for i in range(len(a2)):
    equal = np.equal(np.argmax(y_train[i]), np.argmax(a2[i]))
    correct_pred += equal.astype(float)

In [14]:
(correct_pred/len(y_train)) * 100

83.6

In [15]:
np.equal(np.argmax(y_train), np.argmax(a2)).astype(float)

0.0

In [16]:
y_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])