In [1]:
from pszt import refactor_csv
import numpy as np

In [2]:
x_train = np.load('x_train_no_ignore_no_norm.npy')

In [150]:
np.max(x_train[0])

1.0

In [151]:
# Compute TF for every sentence.
for i in range(len(x_train)):
    sum_of_terms = np.sum(x_train[i])
    x_train[i] /= sum_of_terms
    
D = x_train.shape[0] # num of documents in the corpus
idf = np.zeros(x_train.shape[1]) # zero occurings of words in the corpus

for vector in x_train:
    # Find indexes of non zero values.
    non_zero_indexes = np.nonzero(vector)
    
    # Append vector d at those indexes.
    for idx in non_zero_indexes:
        idf[idx] += 1
        
idf = np.divide(D, idf)
idf = np.log(idf)

x_train *= idf

In [158]:
x_train[5][266]

0.25338460510242844

In [121]:
np.sum(x_train)

3803.9999999999977

In [120]:
# Compute TF for every sentence.
for i in range(len(x_train)):
    sum_of_terms = np.sum(x_train[i])
    x_train[i] /= sum_of_terms

In [37]:
sum_of_terms = np.sum(sentence)

tf = []

tf = sentence/sum_of_terms
#for i, num in enumerate(sentence):
#    tf.append(num/sum_of_terms)

In [41]:
np.sum(sentence)

1.0

In [22]:
D = x_train.shape[0] # num of documents in the corpus

3804

In [111]:
d = np.zeros(x_train.shape[1])

In [75]:
np.nonzero(x_train[0])

(array([  42,  421,  514, 1139, 1699, 2531, 2645, 3617, 4081, 6819, 6996,
        7144]),)

In [112]:
for vector in x_train:
    # Find indexes of non zero values.
    non_zero_indexes = np.nonzero(vector)
    
    # Append vector d at those indexes.
    for idx in non_zero_indexes:
        d[idx] += 1

In [113]:
d

array([  4.,  18., 314., ...,   1.,   1.,  11.])

In [114]:
d

array([  4.,  18., 314., ...,   1.,   1.,  11.])

In [138]:
idf = np.divide(D, d)

In [140]:
idf = np.log(idf)

In [142]:
len(idf)

8257

In [122]:
idf.shape

(8257,)

In [123]:
x_train.shape

(3804, 8257)

In [144]:
x_train[5][266]

0.0625

In [143]:
idf[266]

4.054153681638855

In [145]:
x_train *= idf

In [147]:
x_train[5][266]

0.25338460510242844

In [3]:
refactor_csv.tf_idf('x_train_no_ignore_no_norm.npy', 'x_train_tfidf')

In [4]:
x_train_tfidf = np.load('x_train_tfidf.npy')

In [6]:
x_train_tfidf.shape

(3804, 8257)

In [7]:
x_train.shape

(3804, 8257)

In [2]:
refactor_csv.vectorize_dataset('apple-twitter.csv', 'x_tfidf', 'y_tfidf', tfidf=True)

In [3]:
x_tfidf = np.load('x_tfidf.npy')
x_tfidf[5][266]

0.25338460510242844

In [1]:
from pszt import refactor_csv
import numpy as np

In [2]:
refactor_csv.vectorize_dataset('apple-twitter.csv', 'x_tfidf', 'y_tfidf', tfidf=True)

In [4]:
x_tfidf = np.load('x_tfidf.npy')
y_tfidf = np.load('y_tfidf.npy')
x_tfidf[5][266]

0.25338460510242844

In [6]:
x_tfidf.shape

(3804, 8257)