In [1]:
from net import MLP
import numpy as np

In [2]:
mlp = MLP()

In [3]:
mlp.print_layers()

In [4]:
x_train = np.load('x_train.npy')
y_train = np.load('y_train.npy')
print(f'x_train.shape: {x_train.shape}, y_train.shape: {y_train.shape}')

x_train.shape: (1000, 8257), y_train.shape: (1000, 3)


In [5]:
mlp.add_layer(input_dim=x_train.shape[1], output_dim=1000, activation="relu")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu


In [6]:
mlp.add_layer(input_dim=1000, output_dim=20, activation="relu")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu
1. Layer - input_dim: 1000, output_dim: 20, activation: relu


In [7]:
mlp.add_layer(input_dim=20, output_dim=3, activation="softmax")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu
1. Layer - input_dim: 1000, output_dim: 20, activation: relu
1. Layer - input_dim: 20, output_dim: 3, activation: softmax


In [8]:
mlp.init_layers()

In [9]:
mlp.param_values['w2']

array([[0.09128604, 0.0960539 , 0.08928713, ..., 0.15952392, 0.13883098,
        0.06497602],
       [0.06628767, 0.2009952 , 0.11611471, ..., 0.18553621, 0.11072157,
        0.0161572 ],
       [0.19502732, 0.16106552, 0.16227326, ..., 0.12317598, 0.27680047,
        0.13411581],
       ...,
       [0.03200195, 0.11502592, 0.25257898, ..., 0.06329626, 0.2344428 ,
        0.22117193],
       [0.05360674, 0.26736379, 0.25573189, ..., 0.06952666, 0.10227537,
        0.09561835],
       [0.1282492 , 0.1881052 , 0.26616333, ..., 0.26657986, 0.07447342,
        0.30116168]])

In [10]:
mlp.forward(x_train)

/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:187: RuntimeWarning: invalid value encountered in true_divide
  return expA / expA.sum(axis=1, keepdims=True)


In [11]:
z = np.dot(mlp.memory['a1'], mlp.param_values['w2']) + mlp.param_values['b2']
a = 1/(1+np.exp(-z))
print(z)
print(a)

[[ 84.3361915   86.17374192  88.04708986 ...  91.10345878  90.15896454
   81.95129124]
 [ 94.0767038   95.51028906  97.89545202 ... 100.78702938 100.17827671
   91.21147942]
 [ 78.13157969  79.95370804  81.74426767 ...  84.42610404  83.89278784
   75.9337457 ]
 ...
 [ 94.09802148  95.75794804  97.89972622 ... 100.51229751  99.98378065
   91.10607056]
 [120.85779091 122.97306647 125.22074022 ... 128.17778987 127.09802727
  117.36334444]
 [113.51609049 115.63294472 117.72905542 ... 120.75808268 119.48093501
  109.72063403]]
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [12]:
mlp.train(x_train, y_train)

/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:187: RuntimeWarning: invalid value encountered in true_divide
  return expA / expA.sum(axis=1, keepdims=True)


loss: nan, accuracy: 28.7%


/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:109: RuntimeWarning: divide by zero encountered in log
  cross_entropy_loss = np.sum(-y_true * np.log(y_pred))
/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:109: RuntimeWarning: invalid value encountered in multiply
  cross_entropy_loss = np.sum(-y_true * np.log(y_pred))


In [13]:
mlp.memory['a2']

array([[ 84.3361915 ,  86.17374192,  88.04708986, ...,  91.10345878,
         90.15896454,  81.95129124],
       [ 94.0767038 ,  95.51028906,  97.89545202, ..., 100.78702938,
        100.17827671,  91.21147942],
       [ 78.13157969,  79.95370804,  81.74426767, ...,  84.42610404,
         83.89278784,  75.9337457 ],
       ...,
       [ 94.09802148,  95.75794804,  97.89972622, ..., 100.51229751,
         99.98378065,  91.10607056],
       [120.85779091, 122.97306647, 125.22074022, ..., 128.17778987,
        127.09802727, 117.36334444],
       [113.51609049, 115.63294472, 117.72905542, ..., 120.75808268,
        119.48093501, 109.72063403]])

In [ ]:
for i in range(100):
    mlp.train(x_train, y_train)

/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:168: RuntimeWarning: invalid value encountered in maximum
  return np.maximum(0, x)
/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:172: RuntimeWarning: invalid value encountered in less_equal
  x[x<=0] = 0
/home/kor/Dropbox/version-control/pszt-projekt/pszt/net.py:173: RuntimeWarning: invalid value encountered in greater
  x[x>0] = 1


loss: nan, accuracy: 34.0%
loss: nan, accuracy: 34.0%
loss: nan, accuracy: 34.0%
