In [1]:
from net import MLP
import numpy as np

In [2]:
mlp = MLP()

In [3]:
mlp.print_layers()

In [4]:
x_train = np.load('x_train.npy')
y_train = np.load('y_train.npy')
print(f'x_train.shape: {x_train.shape}, y_train.shape: {y_train.shape}')

x_train.shape: (1000, 8257), y_train.shape: (1000, 3)


In [5]:
mlp.add_layer(input_dim=x_train.shape[1], output_dim=1000, activation="relu")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu


In [6]:
mlp.add_layer(input_dim=1000, output_dim=20, activation="relu")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu
1. Layer - input_dim: 1000, output_dim: 20, activation: relu


In [7]:
mlp.add_layer(input_dim=20, output_dim=3, activation="softmax")
mlp.print_layers()

1. Layer - input_dim: 8257, output_dim: 1000, activation: relu
1. Layer - input_dim: 1000, output_dim: 20, activation: relu
1. Layer - input_dim: 20, output_dim: 3, activation: softmax


In [8]:
mlp.init_layers()

In [9]:
mlp.param_values['w2']

array([[0.00548604, 0.00417872, 0.00584317, ..., 0.00667436, 0.00176829,
        0.00939772],
       [0.00844357, 0.00781857, 0.00773649, ..., 0.00289584, 0.00613755,
        0.0035885 ],
       [0.0054506 , 0.00790642, 0.00171168, ..., 0.00170385, 0.00867165,
        0.00417008],
       ...,
       [0.00631597, 0.00496235, 0.00196661, ..., 0.00014997, 0.0027813 ,
        0.00322009],
       [0.00134574, 0.00925887, 0.00676911, ..., 0.00079903, 0.00384524,
        0.00918386],
       [0.00421566, 0.00258786, 0.00021377, ..., 0.00446141, 0.00875802,
        0.00105812]])

In [10]:
mlp.forward(x_train)

In [11]:
z = np.dot(mlp.memory['a1'], mlp.param_values['w2']) + mlp.param_values['b2']
a = 1/(1+np.exp(-z))
print(z)
print(a)

[[0.30392067 0.30947686 0.29581975 ... 0.30358477 0.2789873  0.31591833]
 [0.40728776 0.41735862 0.3978703  ... 0.40805987 0.37870041 0.41571528]
 [0.2298877  0.23671549 0.22087262 ... 0.22571384 0.20639259 0.23904522]
 ...
 [0.40661899 0.41833895 0.39713285 ... 0.4060521  0.37654949 0.41470012]
 [0.67654038 0.69066003 0.6722436  ... 0.68563508 0.64126667 0.68626106]
 [0.60229574 0.61839894 0.59651126 ... 0.60677424 0.56857337 0.61520251]]
[[0.57540068 0.57675756 0.5734203  ... 0.57531861 0.56929793 0.5783292 ]
 [0.60043736 0.60285102 0.59817587 ... 0.60062258 0.59355962 0.6024575 ]
 [0.55722015 0.55890408 0.55499476 ... 0.5561901  0.55141576 0.55947835]
 ...
 [0.6002769  0.60308571 0.5979986  ... 0.60014087 0.59304061 0.60221434]
 [0.66296611 0.66611374 0.66200536 ... 0.66499523 0.65503974 0.66513467]
 [0.64618136 0.64985432 0.64485773 ... 0.64720461 0.63843392 0.64912665]]


In [12]:
mlp.train(x_train, y_train)

loss: 1100.06, accuracy: 10.5%


In [13]:
mlp.memory['a2']

array([[0.30392067, 0.30947686, 0.29581975, ..., 0.30358477, 0.2789873 ,
        0.31591833],
       [0.40728776, 0.41735862, 0.3978703 , ..., 0.40805987, 0.37870041,
        0.41571528],
       [0.2298877 , 0.23671549, 0.22087262, ..., 0.22571384, 0.20639259,
        0.23904522],
       ...,
       [0.40661899, 0.41833895, 0.39713285, ..., 0.4060521 , 0.37654949,
        0.41470012],
       [0.67654038, 0.69066003, 0.6722436 , ..., 0.68563508, 0.64126667,
        0.68626106],
       [0.60229574, 0.61839894, 0.59651126, ..., 0.60677424, 0.56857337,
        0.61520251]])

In [14]:
for i in range(100):
    mlp.train(x_train, y_train)

loss: 970.36, accuracy: 55.5%
loss: 966.56, accuracy: 55.5%
loss: 944.58, accuracy: 55.5%
loss: 939.88, accuracy: 55.5%
loss: 936.79, accuracy: 55.5%
loss: 934.80, accuracy: 55.5%
loss: 932.99, accuracy: 55.5%
loss: 931.22, accuracy: 55.5%
loss: 929.38, accuracy: 55.5%
loss: 927.40, accuracy: 55.5%
loss: 925.22, accuracy: 55.5%
loss: 922.79, accuracy: 55.5%
loss: 920.03, accuracy: 55.5%
loss: 916.89, accuracy: 55.5%
loss: 913.28, accuracy: 55.5%
loss: 909.13, accuracy: 55.5%
loss: 904.34, accuracy: 55.5%
loss: 898.81, accuracy: 55.8%
loss: 892.46, accuracy: 55.9%
loss: 885.16, accuracy: 56.2%
loss: 876.84, accuracy: 57.4%
loss: 867.44, accuracy: 58.2%
loss: 856.94, accuracy: 59.9%
loss: 845.45, accuracy: 61.5%
loss: 833.27, accuracy: 62.7%
loss: 821.25, accuracy: 65.6%
loss: 811.83, accuracy: 66.0%
loss: 817.77, accuracy: 69.2%
loss: 883.46, accuracy: 62.5%
loss: 1103.52, accuracy: 34.0%
loss: 802.53, accuracy: 66.8%
loss: 809.40, accuracy: 69.9%
loss: 816.60, accuracy: 67.7%
loss: 859